version: "3.9"

services:
  db:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - COCKROACH_DATABASE=stocksdb

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    env_file: ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: ./frontend/.env
    depends_on:
      - backend
